# Generated by Django 4.0.4 on 2022-05-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('measure', models.CharField(max_length=128, verbose_name='единица измерения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена')),
                ('receipt_date', models.DateField(auto_now_add=True, verbose_name='дата поступления')),
                ('supplier', models.CharField(max_length=128, verbose_name='поставщик')),
            ],
        ),
    ]
