# Generated by Django 4.0.4 on 2022-05-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('products', '0004_category_site_product_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sites',
            field=models.ManyToManyField(to='sites.site'),
        ),
    ]
