# Generated by Django 4.0.4 on 2022-06-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_managers_alter_product_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='media/default_product.png', upload_to='media/', verbose_name='изображение'),
        ),
    ]
