# Generated by Django 4.0.4 on 2022-06-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_product.png', upload_to='product_images', verbose_name='изображение'),
        ),
    ]
